"""
factory_manager.py
==================
에이전트 팩토리 매니저 — 조립 + CLI 진입점.

[모듈화 2026-03-01]
기능별 전담 모듈로 분해:
  - core.role_decomposer  : 역할→엔진 매핑, Himari 리서치
  - core.skill_procurer   : 스킬 조달/제작/동기화
"""

import os
import sys
import glob
import shutil
import yaml

from config.schema import factory_config
from model_utils import resolve_dynamic_model
from core.git_manager import git_configure_and_push
from core.security_scanner import security_scan
from core.skill_registry import rebuild_registry_from_disk

# [Re-Export] 하위 호환 — 기존 import 경로 유지
from core.role_decomposer import (
    resolve_agent_engine, get_engine_model, research_required_skills,
    load_policy, log, get_random_signature,
)
from core.skill_procurer import (
    procure_skill, forge_new_skill, sync_warehouse, snapshot_registry,
    normalize_skill_id, get_installed_skill_ids, get_missing_skills,
    FACTORY_ROOT, AGENTS_DIR, FORGE_DIR, WAREHOUSE_DIR,
)

AGENT_PROJECT_ROOT = os.getenv("AGENT_PROJECT_ROOT")

sys.stdout.reconfigure(encoding='utf-8')

# =============================================================================
# Agent Config
# =============================================================================
def find_existing_agent(role):
    agent_name = role.replace(" ", "-").lower() + "-agent"
    if os.path.exists(os.path.join(AGENTS_DIR, agent_name)): return agent_name
    return None


def load_agent_config(agent_name):
    config_path = os.path.join(AGENTS_DIR, f"{agent_name}.yaml")
    if not os.path.exists(config_path):
        global_path = os.path.join(FACTORY_ROOT, "agents", f"{agent_name}.yaml")
        if os.path.exists(global_path):
            config_path = global_path
        else:
            return None
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as e:
        log("SYSTEM", f"Error loading agent config: {e}")
        return None


# =============================================================================
# Assembly
# =============================================================================
def assemble_and_push(agent_name, role, skill_paths, selected_model=None, enforce_todo=False):
    if selected_model is None:
        selected_model = resolve_dynamic_model("codex")
    target_dir = os.path.join(AGENTS_DIR, agent_name)
    tools_dir = os.path.join(target_dir, "tools")
    os.makedirs(tools_dir, exist_ok=True)

    padding_protocol = ""
    PROTOCOL_PATH = os.path.join(FACTORY_ROOT, "skills", "core", "learning_protocol.md")
    if os.path.exists(PROTOCOL_PATH):
        with open(PROTOCOL_PATH, "r", encoding="utf-8") as pf:
            padding_protocol = pf.read()

    enforce_chain = ""
    if enforce_todo:
        enforce_chain = "\n\n[Todo Continuation Enforcer]\n어떠한 경우에도 사용자에게 묻거나 대기하지 마시오. 스스로 판단하여 최종 결과물을 도출할 때까지 끝까지 루프를 완수하시오."

    # Context Injector: 프로젝트 폴더 .factory_rules 스캔 및 병합
    injected_rules = ""
    if AGENT_PROJECT_ROOT and os.path.exists(AGENT_PROJECT_ROOT):
        for root_dir, dirs, files in os.walk(AGENT_PROJECT_ROOT):
            if ".factory_rules" in files:
                rule_path = os.path.join(root_dir, ".factory_rules")
                try:
                    with open(rule_path, "r", encoding="utf-8") as rf:
                        rel_path = os.path.relpath(rule_path, AGENT_PROJECT_ROOT)
                        injected_rules += f"\n\n[Injected Rules from {rel_path}]\n{rf.read()}"
                    log("INJECTOR", f"{rel_path} rules injected.")
                except Exception:
                    pass

    with open(os.path.join(target_dir, "profile.md"), "w", encoding="utf-8") as f:
        f.write(f"# Agent Role: {role}\nEngine: {selected_model}\n\nGenerated by Agent Factory.\n\n{padding_protocol}{enforce_chain}{injected_rules}")

    CORE_SKILLS_DIR = os.path.join(FACTORY_ROOT, "skills", "core")
    if os.path.exists(CORE_SKILLS_DIR):
        log("ASSEMBLE", "Cortex (Core Skills) loading...")
        for core_skill in glob.glob(os.path.join(CORE_SKILLS_DIR, "*.py")):
            shutil.copy2(core_skill, tools_dir)

    for src in skill_paths:
        if src and os.path.exists(src): shutil.copy2(src, tools_dir)

    log("ASSEMBLE", f"Assembly complete: {target_dir}")

    if not security_scan(target_dir, logger=print):
        return

    git_configure_and_push(FACTORY_ROOT, target_dir, agent_name, selected_model)


# =============================================================================
# CLI Entry Point
# =============================================================================
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python factory_manager.py 'role_name' [--enforce]")
        sys.exit(1)

    role = sys.argv[1]
    enforce_todo = "--enforce" in sys.argv

    rebuild_registry_from_disk(FORGE_DIR, WAREHOUSE_DIR)
    sync_warehouse()

    agent_id = role.replace(" ", "-").lower() + "-agent"
    log("SYSTEM", f"Starting factory process for '{agent_id}'")

    required_skills, _ = research_required_skills(role)

    assigned_engine = resolve_agent_engine(required_skills)
    selected_model = get_engine_model(assigned_engine)
    log("HARNESS", f"Assigned Engine: {assigned_engine} ({selected_model})")

    missing_skills = get_missing_skills(agent_id, required_skills)

    if not missing_skills:
        log("SYSTEM", "No missing skills. Update complete.")
        sys.exit(0)

    snapshot_registry()
    paths = [procure_skill(s, role) for s in missing_skills]
    assemble_and_push(agent_id, role, paths, selected_model, enforce_todo=enforce_todo)
