import os
import sys
import glob
import subprocess
import re
import shutil
import google.generativeai as genai

# --- [0] 설정 및 준비 ---
FACTORY_ROOT = os.getcwd()
AGENTS_DIR = os.path.join(FACTORY_ROOT, "agents")
WAREHOUSE_DIR = os.path.join(FACTORY_ROOT, "skills", "warehouse")
FORGE_DIR = os.path.join(FACTORY_ROOT, "skills", "forge")

# [NEW] 안티그래비티 스킬 저장소 (여기에 원하는 깃허브 주소를 넣으세요!)
# 예시: "https://github.com/Significant-Gravitas/AutoGPT" (또는 본인의 스킬 저장소)
ANTIGRAVITY_REPO_URL = "https://github.com/guanyang/antigravity-skills.git"

# API 키 확인
api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    print("❌ [오류] GEMINI_API_KEY가 설정되지 않았습니다.")
    print("   터미널에 다음을 입력하세요: $env:GEMINI_API_KEY='본인의_API_키'")
    sys.exit(1)

genai.configure(api_key=api_key)
model = genai.GenerativeModel('gemini-2.0-flash')

def log(step, msg):
    print(f"[{step}] {msg}")

# --- [보안] 민감 정보 패턴 ---
SENSITIVE_PATTERNS = [
    r"sk-[a-zA-Z0-9]{20,}", r"AIza[0-9A-Za-z-_]{35}", 
    r"ghp_[a-zA-Z0-9]{20,}", r"xoxb-[a-zA-Z0-9-]{10,}"
]

def security_scan(directory):
    log("SECURITY", f"🔍 보안 검색 중: {directory}")
    is_safe = True
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith((".py", ".md", ".yaml", ".txt", ".json", ".sh")):
                try:
                    with open(os.path.join(root, file), "r", encoding="utf-8", errors="ignore") as f:
                        content = f.read()
                        for pattern in SENSITIVE_PATTERNS:
                            if re.search(pattern, content):
                                log("SECURITY", f"🚨 민감 정보 발견! 파일: {file}")
                                is_safe = False
                except: pass
    if not is_safe:
        log("SECURITY", "⛔ 보안 위규 사항 발생! (Git Push 중단됨)")
        return False
    return True
# --- [NEW] 깃허브 창고 동기화 (스킬 수입) ---
def sync_warehouse():
    log("WAREHOUSE", "📦 깃허브에서 최신 스킬을 확인하는 중...")
    
    if not os.path.exists(WAREHOUSE_DIR):
        # 폴더가 없으면 -> 깃허브에서 통째로 다운로드 (Clone)
        log("WAREHOUSE", "🚀 스킬 창고가 비었습니다. 깃허브에서 다운로드합니다...")
        try:
            subprocess.run(["git", "clone", ANTIGRAVITY_REPO_URL, WAREHOUSE_DIR], check=True)
            log("WAREHOUSE", "✅ 스킬 다운로드 완료!")
        except Exception as e:
            log("WAREHOUSE", f"⚠️ 스킬 다운로드 실패 (주소 확인 필요): {e}")
    else:
        # 폴더가 있으면 -> 최신 버전으로 업데이트 (Pull)
        log("WAREHOUSE", "🔄 기존 창고를 업데이트합니다...")
        try:
            subprocess.run(["git", "-C", WAREHOUSE_DIR, "pull"], check=True)
            log("WAREHOUSE", "✅ 업데이트 완료!")
        except Exception as e:
            log("WAREHOUSE", f"⚠️ 업데이트 실패 (로컬 모드로 진행): {e}")

# --- [기능] 에이전트 생성 및 조립 ---
def find_existing_agent(role):
    agent_name = role.replace(" ", "-").lower() + "-agent"
    if os.path.exists(os.path.join(AGENTS_DIR, agent_name)): return agent_name
    return None

def research_required_skills(role):
    log("RESEARCH", f"'{role}' 스킬 리서치 중...")
    try:
        prompt = f"Role: {role}. Recommend 2-3 Python CLI tool names (comma separated, English only). Example: web_search, data_loader"
        response = model.generate_content(prompt)
        return [s.strip() for s in response.text.split(',')]
    except: return []

def procure_skill(skill_name, role):
    found = glob.glob(os.path.join(WAREHOUSE_DIR, "**", f"{skill_name}.py"), recursive=True)
    if found: return found[0]
    
    forge_path = os.path.join(FORGE_DIR, f"{skill_name}.py")
    if os.path.exists(forge_path): return forge_path

    return forge_new_skill(skill_name, role)

def forge_new_skill(skill_name, role):
    log("FORGE", f"⚠️ 스킬 없음. '{skill_name}' 제작 시작...")
    os.makedirs(FORGE_DIR, exist_ok=True)
    output_path = os.path.join(FORGE_DIR, f"{skill_name}.py")
    prompt = f"Write Python CLI tool '{skill_name}.py' for role '{role}'. Use argparse. No hardcoded keys. Output code only."
    try:
        response = model.generate_content(prompt)
        code = response.text.replace("```python", "").replace("```", "")
        with open(output_path, "w", encoding="utf-8") as f: f.write(code)
        log("FORGE", f"🔥 제작 완료: {output_path}")
        return output_path
    except: return None

def assemble_and_push(agent_name, role, skill_paths):
    target_dir = os.path.join(AGENTS_DIR, agent_name)
    tools_dir = os.path.join(target_dir, "tools")
    os.makedirs(tools_dir, exist_ok=True)
    
    with open(os.path.join(target_dir, "profile.md"), "w", encoding="utf-8") as f:
        f.write(f"# Role: {role}\nGenerated by Factory Manager")

    for src in skill_paths:
        if src and os.path.exists(src): shutil.copy2(src, tools_dir)

    log("ASSEMBLE", f"에이전트 조립 완료: {target_dir}")
    
    if not security_scan(target_dir): return 

    log("GIT", "GitHub로 전송 중...")
    try:
        subprocess.run(["git", "add", "."], check=True)
        subprocess.run(["git", "commit", "-m", f"feat: Created {agent_name}"], check=True)
        subprocess.run(["git", "push"], check=True)
        log("GIT", "✅ Push 성공!")
    except: log("GIT", "⚠️ Git 변경 사항이 없거나 설정 오류")


if __name__ == "__main__":
    # 1. 사용자가 역할을 입력했는지 확인
    if len(sys.argv) < 2:
        print("사용법: python factory_manager.py '원하는 역할'")
        sys.exit(1)
    
    role = sys.argv[1]

    # [NEW] 2. 공장 가동 전에 깃허브에서 스킬부터 가져오기! (여기에 추가됨)
    # (위에서 만든 sync_warehouse 함수가 여기서 실행됩니다)
    try:
        sync_warehouse() 
    except NameError:
        print("⚠️ sync_warehouse 함수가 정의되지 않아 건너뜁니다.")

    # 3. 이미 만든 에이전트인지 확인
    if find_existing_agent(role):
        print("이미 존재하는 에이전트입니다.")
        sys.exit(0)
        
    # 4. 리서치 -> 스킬 확보 -> 조립 -> 깃허브 전송
    skills = research_required_skills(role)
    paths = [procure_skill(s, role) for s in skills]
    assemble_and_push(role.replace(" ", "-").lower() + "-agent", role, paths)