import os
import json
from datetime import datetime

def propose(ctx):
    return {
        "description": "Generate a UI/UX design review checklist.",
        "required_keys": ["project_type"],
        "optional_keys": ["focus_area"]
    }

def apply(ctx):
    try:
        project = ctx.get("project_type", "General")
        focus = ctx.get("focus_area", "Usability")
        artifacts_dir = ctx.get("artifacts_dir", ".")
        
        filename = f"design_review_{project.replace(' ', '_').lower()}.md"
        filepath = os.path.join(artifacts_dir, filename)

        checklist = f"""# 🎨 UI/UX Design Review: {project}
**Date:** {datetime.now().strftime("%Y-%m-%d")}
**Focus Area:** {focus}

## 1. Visual Hierarchy
- [ ] Is the primary call-to-action (CTA) distinct?
- [ ] Are headings clearly differentiated by size/weight?
- [ ] Is whitespace used effectively to group related elements?

## 2. Accessibility (a11y)
- [ ] Do all images have alt text?
- [ ] Is the color contrast ratio at least 4.5:1?
- [ ] Can the interface be navigated via keyboard?

## 3. Consistency (Design System)
- [ ] Are brand colors used correctly?
- [ ] Is typography consistent with the style guide?
- [ ] Do button styles match across pages?

## 4. User Flow & {focus}
- [ ] Is the feedback loop clear (Loading -> Success/Error)?
- [ ] Are error messages helpful and human-readable?
- [ ] (Specific check for {focus})

---
*Generated by Saiba Midori (UI/UX Director)*
"""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(checklist)

        return {
            "ok": True,
            "message": f"Generated Design Review Checklist: {filepath}",
            "file_path": filepath
        }
    except Exception as e:
        return {"ok": False, "error": str(e)}

def test(ctx):
    return apply({
        "project_type": "Landing Page",
        "focus_area": "Conversion",
        "artifacts_dir": ctx.get("artifacts_dir", ".")
    })
