import os
import json
from datetime import datetime

# 주의: 실제 웹 검색 API(SerpAPI 등)가 연동되지 않은 환경에서는 
# LLM의 내장 지식을 활용하여 '리서치 보고서' 형식을 갖추는 것에 집중합니다.

def propose(ctx):
    return {
        "description": "기술 주제에 대한 심층 리서치 보고서를 작성합니다.",
        "required_keys": ["topic"],
        "optional_keys": ["depth", "output_format"]
    }

def apply(ctx):
    try:
        data_dir = ctx.get("data_dir", ".")
        artifacts_dir = ctx.get("artifacts_dir", ".")
        
        topic = ctx.get("topic")
        depth = ctx.get("depth", "summary") # summary, detailed
        
        # 실제로는 여기서 Google Search API 등을 호출해야 하지만,
        # 현재 환경(Local LLM Only)에서는 '구조화된 보고서 템플릿'을 생성하여 
        # 에이전트가 내용을 채우도록 유도하거나, 더미 데이터를 생성합니다.
        
        # 여기서는 스킬 자체가 '보고서 파일'을 생성하는 역할을 수행합니다.
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_{timestamp}.md"
        filepath = os.path.join(artifacts_dir, filename)
        
        # 보고서 템플릿 생성 (실제 내용은 에이전트가 채우거나, 이 스킬이 LLM을 호출해야 함)
        # 현재 구조상 스킬이 LLM을 직접 호출하기는 어려우므로(agent_launcher가 LLM 관리),
        # '리서치 결과 파일' 틀을 만들어주는 것으로 합니다.
        
        report_content = f"""# 📑 Research Report: {topic}
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Author: Himari (Super Research Architect)

## 1. Executive Summary
(이 주제의 핵심 내용을 3줄로 요약합니다.)

## 2. Key Technology Analysis
### 2.1 Current State
- 트렌드: ...
- 주요 기술: ...

### 2.2 Pros & Cons
| Pros | Cons |
|------|------|
| ... | ... |

## 3. Recommendation
(초천재 미소녀의 결론)

---
*Generated by Himari Research Skill*
"""
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_content)
            
        return {
            "ok": True,
            "message": f"Research report template generated for '{topic}'",
            "report_path": filepath,
            "note": "내용은 에이전트가 추가적으로 채워넣어야 합니다."
        }
        
    except Exception as e:
        return {"ok": False, "error": str(e)}

def test(ctx):
    ctx["topic"] = "AI Agent Patterns"
    res = apply(ctx)
    result_path = res.get("report_path")
    
    if res["ok"] and result_path and os.path.exists(result_path):
        # 테스트 파일 삭제
        os.remove(result_path)
        return {"ok": True, "message": "Research report generation tested successfully."}
    else:
        return res
