import os
import json
from datetime import datetime
import sys
import subprocess


def _extract_answer(raw_text: str) -> str:
    text = (raw_text or "").strip()
    if not text:
        return ""
    try:
        data = json.loads(text)
        value = data.get("value", {}) if isinstance(data, dict) else {}
        if isinstance(value, dict):
            ans = str(value.get("answer") or "").strip()
            if ans:
                return ans
            raw_response = str(value.get("raw_response") or "").strip()
            if raw_response:
                return raw_response[:2000]
    except Exception:
        pass
    return text


def _is_auth_error(stderr_text: str) -> bool:
    s = (stderr_text or "").lower()
    flags = [
        "authentication expired",
        "rpc error 16",
        "clientauthenticationerror",
        "run 'nlm login'",
    ]
    return any(f in s for f in flags)


def _reauth_notebooklm() -> bool:
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONUTF8"] = "1"
    try:
        p = subprocess.run(
            [sys.executable, "-m", "notebooklm_tools.cli.main", "login"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            env=env,
            timeout=180,
        )
        return p.returncode == 0
    except Exception:
        return False


def _query_notebooklm(query: str) -> str:
    """
    Query NotebookLM, auto re-auth once if token expired.
    """
    try:
        target_notebook_id = "eaa34a54-a898-46a0-835a-cdb6024887f0"
        cmd = [
            sys.executable,
            "-m",
            "notebooklm_tools.cli.main",
            "query",
            "notebook",
            target_notebook_id,
            query,
        ]
        env = os.environ.copy()
        env["PYTHONIOENCODING"] = "utf-8"
        env["PYTHONUTF8"] = "1"

        p = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", env=env, timeout=120)
        if p.returncode != 0 and _is_auth_error(p.stderr or ""):
            if _reauth_notebooklm():
                p = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", env=env, timeout=120)

        if p.returncode != 0:
            return f"(Error querying NotebookLM: {(p.stderr or '').strip()})"
        return _extract_answer(p.stdout)
    except Exception as e:
        return f"(Connection Error: {e})"


def propose(ctx):
    return {
        "description": "기술 주제 기반 리서치 보고서를 작성합니다.",
        "required_keys": ["topic"],
        "optional_keys": ["depth", "output_format"],
    }


def apply(ctx):
    try:
        artifacts_dir = ctx.get("artifacts_dir", ".")
        os.makedirs(artifacts_dir, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_{timestamp}.md"
        filepath = os.path.join(artifacts_dir, filename)

        topic = ctx.get("topic") or "General Research"
        research_content = _query_notebooklm(
            f"Detailed research on: {topic}. focus on key technology analysis, pros/cons, and recommendations."
        )

        report_content = f"""# Research Report: {topic}
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Author: Himari (Super Research Architect)

## 1. Executive Summary
(Research based on NotebookLM Secret Archive)

## 2. Key Technology Analysis
{research_content}

## 3. Recommendation
(Review the above analysis and make a decision.)

---
*Generated by Himari Research Skill*
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_content)

        return {
            "ok": True,
            "message": f"Research report generated for '{topic}'",
            "report_path": filepath,
        }
    except Exception as e:
        return {"ok": False, "error": str(e)}


def test(ctx):
    tmp_ctx = dict(ctx or {})
    tmp_ctx["topic"] = "AI Agent Patterns"
    res = apply(tmp_ctx)
    path = res.get("report_path")
    if res.get("ok") and path and os.path.exists(path):
        try:
            os.remove(path)
        except Exception:
            pass
        return {"ok": True, "message": "Research report generation tested successfully."}
    return res
