import os
import json
from datetime import datetime

import sys
import subprocess

# 주의: 실제 웹 검색 API(SerpAPI 등)가 연동되지 않은 환경에서는 
# NotebookLM(비밀 서고)을 활용하여 '리서치 보고서' 내용을 채웁니다.

def _query_notebooklm(query: str) -> str:
    """
    NotebookLM CLI를 통해 질문을 수행합니다.
    기본 노트북 ID: eaa34a54-a898-46a0-835a-cdb6024887f0
    """
    try:
        target_notebook_id = "eaa34a54-a898-46a0-835a-cdb6024887f0"
        
        cmd = [
            sys.executable, "-m", "notebooklm_tools.cli.main",
            "query", "notebook",
            target_notebook_id,
            query
        ]
        
        env = os.environ.copy()
        env["PYTHONIOENCODING"] = "utf-8"
        
        p = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding='utf-8',
            env=env,
            timeout=120 # 내용 생성에 시간이 걸림
        )
        
        if p.returncode != 0:
            return f"(Error querying NotebookLM: {p.stderr.strip()})"
            
        return p.stdout.strip()
        
    except Exception as e:
        return f"(Connection Error: {e})"

def propose(ctx):
    return {
        "description": "기술 주제에 대한 심층 리서치 보고서를 작성합니다.",
        "required_keys": ["topic"],
        "optional_keys": ["depth", "output_format"]
    }

def apply(ctx):
    try:
        data_dir = ctx.get("data_dir", ".")
        artifacts_dir = ctx.get("artifacts_dir", ".")
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_{timestamp}.md"
        filepath = os.path.join(artifacts_dir, filename)
        
        topic = ctx.get("topic")
        depth = ctx.get("depth", "summary") # summary, detailed
        
        # 1. NotebookLM 리서치 수행
        print(f"🔎 [Skill] NotebookLM에서 '{topic}'에 대해 연구 중...")
        research_content = _query_notebooklm(f"Detailed research on: {topic}. focus on key technology analysis, pros/cons, and recommendations.")
        
        # 2. 보고서 작성
        report_content = f"""# 📑 Research Report: {topic}
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Author: Himari (Super Research Architect)

## 1. Executive Summary
(Research based on NotebookLM Secret Archive)

## 2. Key Technology Analysis
{research_content}

## 3. Recommendation
(Review the above analysis and make a decision.)

---
*Generated by Himari Research Skill*
"""
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_content)
            
        return {
            "ok": True,
            "message": f"Research report template generated for '{topic}'",
            "report_path": filepath,
            "note": "내용은 에이전트가 추가적으로 채워넣어야 합니다."
        }
        
    except Exception as e:
        return {"ok": False, "error": str(e)}

def test(ctx):
    ctx["topic"] = "AI Agent Patterns"
    res = apply(ctx)
    result_path = res.get("report_path")
    
    if res["ok"] and result_path and os.path.exists(result_path):
        # 테스트 파일 삭제
        os.remove(result_path)
        return {"ok": True, "message": "Research report generation tested successfully."}
    else:
        return res
